### ISSUE TITLE
[Bug] No public constructor available for IActiveRegionHelper with Prism.Unity.Forms

### ISSUE THREAD

**Issue by tomaswinston** [PrismLibrary/Prism#2227]
### Description
In using the latest release of Prism.Forms, Prism.Unity.Forms and Prism.Forms.Regions I receive the following error when attempting to call `_regionManager.RequestNavigate`.

`No public constructor is available for type Prism.Regions.IActiveRegionHelper`

This only happens since I updated my Nuget Package references to use the latest `8.0.0.1909` release. Prior to this, I was using `8.0.0.1850-pre` which worked fine. Perhaps I have missed something in the configuration for using Regions but I didn't think so.

### Steps to Reproduce

1. Debug the app in either Android or iOS
2. Upon clicking the "Load Module" button - which executes a command calling the `regionManager.RequestNavigate` method, the application crashes with the aforementioned error i.e. `No public constructor is available for type Prism.Regions.IActiveRegionHelper`

### Expected Behavior
A module is loaded into the specified region.

### Actual Behavior
Exception is thrown `No public constructor is available for type Prism.Regions.IActiveRegionHelper`

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: 8.0.0.1850-pre
- Xamarin.Forms version: 4.8.0.1364 +
- IDE: Visual Studio 2019 and Visual Studio for Mac

### Reproduction Link
https://github.com/tomaswinston/TestPrismModules

**Comment by dansiegel** [comment]
your sample seems to be missing some resources and does not replicate your issue.

**Comment by tomaswinston** [comment]
Uh oh. Embarrassing! Sorry Dan. You'd imagine that if someone was going to submit a bug they would at least confirm that they had uploaded the project repo properly - more than a little embarrassing! Very sorry about that. 
I have updated the repo and tested it. It throws an exception in the ExecuteLoadModuleCommand method of the MainPageViewModel of the main TestPrismModules project. Thanks.

**Comment by dansiegel** [comment]
It would seem that for some reason it's missing the mapping for the IActiveRegionHelper due to a bug in the UnityContainerExtension which has been fixed by #2249. You have a couple of possible solutions:

- Use Prism.DryIoc.Forms
- If you're a sponsor you can access the CI feed which already has the fix
- Update your code to duplicate the RegisterMany call from the Prism.Forms.Regions

**Comment by FeedLab** [comment]
When will this fix be public. I use 8.0.0.1909 NuGet packages and still have the problem.
