### ISSUE TITLE
[Bug] [Forms] [UWP] Functional and visual issues when using tabbed page navigation

### ISSUE THREAD

**Issue by BurkusCat** [PrismLibrary/Prism#2362]
### Description

I am attempting to navigate from a ContentPage to a TabbedPage with 3 tabs. When I do this on UWP, the 'UWP back button' briefly appears and then disappears. This means you can't navigate back to the original page. After navigation, there is a large blank empty space between the tab page title and the tabs. I have a button that programmatically switches tabs like this: `await NavigationService.SelectTabAsync("PlayPage");` - after doing this, the tab does switch but the wrong tab "appears" selected.

This navigation works perfectly on Android.

I've tried working around the issue by not wrapping the tabs in NavigationPages but that breaks SelectTabAsync.

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage
    x:Class="TabRepro.Views.TriTabbedPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:pages="clr-namespace:TabRepro.Views"
    Title="Tabbed page">
    <TabbedPage.Children>
        <NavigationPage Title="Play">
            <x:Arguments>
                <pages:PlayPage />
            </x:Arguments>
        </NavigationPage>
        <NavigationPage Title="Choose">
            <x:Arguments>
                <pages:ChoosePage />
            </x:Arguments>
        </NavigationPage>
        <NavigationPage Title="Find">
            <x:Arguments>
                <pages:FindPage />
            </x:Arguments>
        </NavigationPage>
    </TabbedPage.Children>
</TabbedPage>
```

### Steps to Reproduce

1. Navigate ContentPage -> TabbedPage (with three tabs + viewmodels for each tab)
2. On one of the tabs, have a button that navigates to another tab

### Expected Behavior
Can navigate back to the homepage. No visual issues on the tabbed page. Programmatic tab switching works.

### Actual Behavior
Cannot navigate back to the homepage as the back button is gone. Blank space between title and tabs (UI). Wrong tab appears selected after doing programmatic tab switching (UI).

### Basic Information

- Version with issue: 8.0.0.1909
- Last known good version: N/A
- Xamarin.Forms version: 5.0.0.2012
- IDE: 16.8.2 VS 2019

### Screenshots
Sorry for the bad scribbles on the screenshots lol
![image](https://user-images.githubusercontent.com/7528322/110240555-73121280-7f44-11eb-8338-6a9403056618.png)
![image](https://user-images.githubusercontent.com/7528322/110240605-a94f9200-7f44-11eb-9e8a-b324c34e8cfa.png)
![image](https://user-images.githubusercontent.com/7528322/110240609-afde0980-7f44-11eb-8b00-d9236b09006d.png)
![image](https://user-images.githubusercontent.com/7528322/110240643-dd2ab780-7f44-11eb-9c33-f5b460554900.png)

### Reproduction Link
[TabRepro.zip](https://github.com/PrismLibrary/Prism/files/6097143/TabRepro.zip)

**Comment by brianlagunas** [comment]
Tabbed navigation in v8 is broken. See #2218. This bug has been fixed, but has not been released to NuGet yet. If you are a GitHub sponsor of Dan or myself for $10 or more, you can have access tot he nightly builds that contain this fix. Otherwise, you'll have to wait until the official release which has no scheduled date as of today.

**Comment by brianlagunas** [comment]
You could also downgrade prism to v7 to avoid this issue.

**Comment by BurkusCat** [comment]
@brianlagunas I think these issues are different from the one you have linked. I have downgraded to 7.2.0.1422 and the issues are still present.

Programmatic tab switching **is** working for my use case but the other issues in the screenshots exist for Prism 7 and Prism 8.

**Comment by brianlagunas** [comment]
Prism has no control over the visual rendering of the UI on any platform. Prism calls the XF APIs directly. You could also be experiencing an XF bug noted in #1367
