### ISSUE TITLE
[XF] NavigationPage handling incomplete (tested in Xamarin UWP project)

### ISSUE THREAD

**Issue by ChristianRiedl** [PrismLibrary/Prism#777]
When navigating back using the UWP **GoBack** button **PageNavigationService** does not track the navigation action (calling **INavigationAware** functions, updating current page in **PageNavigationService**). The reason is clear as it is done independently by Xamarin Forms and **PageNavigationService** does not listen on the **NavigationPage** events. 

The consequence in my project was that I could only navigate once from _NavigationPage_ to some _ContentPage_. Going back and navigating once more to the _ContentPage_ failed.   

Adding some code which repairs the **PageNavigationService.Page** when the **NavigationPage.Popped** event occurs, solved the problem for me. 

If required I can send a test project, but I think it is clear, what is going on.

**Comment by brianlagunas** [comment]
This is a known issue.  There is currently no API available that allows Prism to respond to all navigation events, both modal and non-modal, invoked by the hardware/software device buttons in order to call the INavigationAware methods.

**Comment by brianlagunas** [comment]
This has been fixed.

**Comment by KalpeshChheda** [comment]
In UWP software back button is still not working.
Xamarin forms 2.3.2.127

**Comment by brianlagunas** [comment]
You need to be using the Prism for XF 6.3 Preview.  This is not available in 6.2.

**Comment by KalpeshChheda** [comment]
Yup I tried Prism for XF 6.3.0-pre1.  In UWP and in android as well.

No INavigationAware Methods are getting fired (Current Page of) OnNavigatedFrom & (Next Page of)OnNavigatedTo 

Xamarin forms 2.3.2.127,
Xamarin Updates 4.2.1.62
Android 4.4 Emulator,
UWP 14393

**Comment by KalpeshChheda** [comment]
I got the issue 
Navigating from XAML is not working.
Using NavigateAsync is working fine.

**Comment by brianlagunas** [comment]
> I got the issue 
Navigating from XAML is not working.
Using NavigateAsync is working fine.

What do you mean?  You don't navigate from XAML with Prism.  The INavigationService is only available in the ViewModels.

**Comment by KalpeshChheda** [comment]
Actually I had code like this.

In App.xaml.cs
`NavigateAsync(nameof(HomeMasterDetailPage))`

In HomeMasterDetailPage.xaml
```
<MasterDetailPage.Detail>
    <NavigationPage >
      <x:Arguments>
        <views:HomePage/>
      </x:Arguments>
    </NavigationPage>
  </MasterDetailPage.Detail>
```
Ya I realized NavigationPage is not same as Prism NavigationPage. 
So I have updated code in In App.xaml.cs to
`NavigateAsync(HomeMasterDetailPage/HomeNavigationPage/HomePage);`

And Removed 
```
<MasterDetailPage.Detail>
    <NavigationPage >
      <x:Arguments>
        <views:HomePage/>
      </x:Arguments>
    </NavigationPage>
  </MasterDetailPage.Detail>
```
Thanks.
